### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by imbaniac** [SaLiHub/Sorting-table-Vanilla-Js#1]
**Минусы**
- Данные статичны (не генирируются при загрузке страницы) и неинформативны
- var уже морально устарел

**Плюсы**
- Ок vanilla js
- Комменты в коде и ридми
- BEM

**Итого**
Требования задания не выполнены (данные статичны + неинформативны). Тестовое не пройдено, мы принимаем решение отказать.

**Comment by heinpen** [comment]
Спасибо за фидбек.

**Comment by heinpen** [comment]
Теперь данные не статичны. И "var" не используется.
